### ISSUE TITLE
unrecognized import path "math/bits"

### ISSUE THREAD

**Issue by KufuT** [gdrive-org/gdrive#308]
`# go get github.com/prasmussen/gdrive
package github.com/prasmussen/gdrive
	imports golang.org/x/oauth2
	imports golang.org/x/net/context
	imports golang.org/x/oauth2/google
	imports cloud.google.com/go/compute/metadata
	imports github.com/sabhiram/go-git-ignore
	imports github.com/soniakeys/graph
	imports github.com/soniakeys/bits
	imports math/bits: unrecognized import path "math/bits"`

Any suggestions?

**Comment by spierepf** [comment]
I think you might be using an old version of go. When I upgraded from 1.3 to 1.9 I stopped getting the math/bits error.
