### ISSUE TITLE
Error to list archives repository in drive

### ISSUE THREAD

**Issue by andin02** [gdrive-org/gdrive#417]
I installed GDRIVE in Debian 9, when typing the "gdrive list" command, it synchronizes, so when it tries to read the files from the drive this error occurs:

root@samba:/usr/local/bin# gdrive list
Authentication needed
Go to the following url in your browser:
https://accounts.google.com/o/oauth2/auth?access_type=offline&client_id=36711622             1053-7n0vf5akeru7on6o2fjinrecpdoe99eg.apps.googleusercontent.com&redirect_uri=ur             n%3Aietf%3Awg%3Aoauth%3A2.0%3Aoob&response_type=code&scope=https%3A%2F%2Fwww.goo             gleapis.com%2Fauth%2Fdrive&state=state

Enter verification code: 4/uQDPq8-lMzcFC5xkkIeqkL25H1TTFXqxxjwRPbdklI56vvPlwuB9i             Yk
Failed to list files: Get https://www.googleapis.com/drive/v3/files?alt=json&fie             lds=nextPageToken%2Cfiles%28id%2Cname%2Cmd5Checksum%2CmimeType%2Csize%2CcreatedT             ime%2Cparents%29&orderBy=&pageSize=30&q=trashed+%3D+false+and+%27me%27+in+owners             : dial tcp [2800:3f0:4001:80d::200a]:443: connect: network is unreachable

What can it be?

**Comment by mbenlioglu** [comment]
Can you do it in browser or similar? Error message seems to indicate a network problem. You cannot establish HTTPS connection

**Comment by mbenlioglu** [comment]
Closing until further information
