### ISSUE TITLE
I am willing to maintain, fork at github.com/tripLr/gdrive for pull requests

### ISSUE THREAD

**Issue by tripLr** [gdrive-org/gdrive#432]
I love this tool. I am willing to help maintain it. If you have code to contibute, a readme update, and how to, please issue a pull request on my fork.

thanks
tripLr

**Comment by mbenlioglu** [comment]
I would contribute as well, maybe firstly, contacting @prasmussen for write access to the repo would be better?

**Comment by tripLr** [comment]
I didn't know that was possible. I have it forked already.

**Comment by mbenlioglu** [comment]
We're resuming active maintenance soon
