### ISSUE TITLE
Need explanation of 403 rate limit exceeded

### ISSUE THREAD

**Issue by lmiol** [gdrive-org/gdrive#435]
Hi there
i need explanation for some limits (thx in advance)
Limit 1000 requests per 100 seconds
i have api key requests to get files.

and if i using this requests from 5 devices i will be like 1 user?
or like 5 users?

**Comment by mbenlioglu** [comment]
By default an application key for Drive API has 3 different rate limits

- 1,000,000,000 queries per day
- 10,000 queries per 100 seconds
- 1,000 queries per 100 seconds per user (determined by IP address of the query origin)

So about your question
> and if i using this requests from 5 devices i will be like 1 user?

If they don't share IP addresses that means they'll be treated as 5 different users. 

You can also track your rate limit usage from [Google APIs Console](https://code.google.com/apis/console). Select your project, which your key belongs, and go to quotes section 
![image](https://user-images.githubusercontent.com/18167175/52958404-0f403f80-33a5-11e9-8454-2e07205a0331.png)

**Comment by lmiol** [comment]
Thank you
