### ISSUE TITLE
Failed to find root dir: googleapi

### ISSUE THREAD

**Issue by Solution-TV** [gdrive-org/gdrive#443]
Ubuntu server 14.4 64 bit

problem is start from 3 week every time im try to up lode file i get this error

Starting sync...
Failed to find root dir: googleapi: Error 403: Rate Limit Exceeded, rateLimitExceeded
Starting sync...
Failed to find root dir: googleapi: Error 403: Rate Limit Exceeded, rateLimitExceeded

i think first my account have limit i speak with google drive they say limit per 1 days i can up lode 2 TB

i create new account at google drive and i connecting with my server still give me same error , google drive they change something in api and the program stop working can you advice me what i have to do to solve the problem ?

**Comment by mbenlioglu** [comment]
The workaround for `Error 403: Rate Limit Exceeded` errors are described in #426 please check that. Possible built-in solutions will be investigated soon.

**Comment by mbenlioglu** [comment]
Duplicate of #392
