### ISSUE TITLE
50% failure rate to gather info with  gdrive info <url> | grep Modified

### ISSUE THREAD

**Issue by DaveFurbag** [gdrive-org/gdrive#445]
While the info command seems to have a 100% success rate, however when using grep to return just one line of the results it fails to give any result about 50% of the time.  Weird, eh.

The help for grive info doesn't make sense for the info subcommand, or I'm expecting different detail from it.

**Comment by mbenlioglu** [comment]
It's most likely caused by API limit issue that currently everyone experiencing. Check #426 for workaround for API limits, until we introduce an official fix

**Comment by mbenlioglu** [comment]
Can you confirm whether it's related to API limit issue?

**Comment by mbenlioglu** [comment]
Closing, reopen if you have followup.
