### ISSUE TITLE
What should i do, if i want uninstall/upgrade to latest version gdrive

### ISSUE THREAD

**Issue by ninmega** [gdrive-org/gdrive#446]
First time using gdrive, I just trying install it following online tutorial which is current version is gdrive: 2.0.1. Then now I want uninstall / upgrade latest version which is appropriate to my OS, ubuntu 64bit

Thanks in advance

**Comment by mbenlioglu** [comment]
To uninstall you can simply remove `gdrive` binary and `~/.gdrive/` folder.
To update replace your `gdrive` binary with the appropriate one from [here](https://github.com/gdrive-org/gdrive#downloads)

We'll include an installation script in a future release.
