### ISSUE TITLE
save file name like fileId

### ISSUE THREAD

**Issue by flexhack** [gdrive-org/gdrive#447]
Hi, how i can download file and save him name as "fileId" ?

**Comment by mbenlioglu** [comment]
I'm not sure if I understood correctly, but if you want to download a file with different name you can use something like this

    $ gdrive download <FILE_ID> --stdout > /path/to/file/filename

**Comment by flexhack** [comment]
Yes exactly, thanks you !

**Comment by flexhack** [comment]
> I'm not sure if I understood correctly, but if you want to download a file with different name you can use something like this
> 
> ```
> $ gdrive download <FILE_ID> --stdout > /path/to/file/filename
> ```
How can this be done for all files in a folder?

**Comment by mbenlioglu** [comment]
There's no built-in way of doing this, it doesn't really makes sense to have it either, but you can write a small script to rename them all after downloading. Something like this:

    # Get info about contents of folder
    META=$(gdrive list --no-header --name-width 0 -q "'FOLDER_ID' in parents")

    # Extract fileID's and names, then use mv command to rename
    echo "$META" | awk -F"  +" '{sub($2, "\"&\""); print $2,$1}' | xargs -L1 mv

**Comment by flexhack** [comment]
> There's no built-in way of doing this, it doesn't really makes sense to have it either, but you can write a small script to rename them all after downloading. Something like this:
> 
> ```
> # Get info about contents of folder
> META=$(gdrive list --no-header --name-width 0 -q "'FOLDER_ID' in parents")
> 
> # Extract fileID's and names, then use mv command to rename
> echo "$META" | awk -F"  +" '{sub($2, "\"&\""); print $2,$1}' | xargs -L1 mv
> ```

I did it differently, I had to use gdrive + rclone 
`#!/bin/bash

catid="18F0NMeVDGqtMbWzi6RWESuOC6c58gYhD"
FILE=$HOME/Downloads/$catid.csv

rclone lsf --format imtp --csv --separator ";" --files-only --drive-root-folder-id=$catid gdrive: \
| sed 's%application/msword%.doc%g' | sed 's%application/vnd.openxmlformats-officedocument.wordprocessingml.document%.docx%g' \
| sed 's%application/rtf%.rtf%g' | sed 's%application/pdf%.pdf%g' | sed 's%application/vnd.ms-excel%.xls%g' \
| sed 's%application/vnd.openxmlformats-officedocument.spreadsheetml.sheet%.xlsx%g' | sed 's%application/zip%.zip%g'  | sed 's%application/x-rar%.rar%g' \
| sed 's%application/x-zip-compressed%.zip%g' | sed 's%application/msword%.doc%g' | sed 's%application/json%.doc%g' > $FILE 

while read LINE; do
	IFS=";" 
     set -- $LINE
     name=$1
     ext=$2
     gdrive download  $name --stdout > /Users/flex/Downloads/files/$name$ext
done < $FILE`

**Comment by mbenlioglu** [comment]
Sending separate download requests to API is both slow and hammers the API limit. You should avoid it. Downloading files in single query and then renaming them on local should be the method you should follow.
