### ISSUE TITLE
Feature Request: Ignore specific files/directories

### ISSUE THREAD

**Issue by nlistgarten** [gdrive-org/gdrive#448]
Requesting a new feature: an --ignore flag which allows the user to ignore a specific file or directory. Example: `gdrive sync upload --ignore /dev/ --dry-run / xxxxxdriveparentidxxxx`, which would ignore the /dev/ folder in the root directory, but perform a sync upload on everything else.

**Comment by mbenlioglu** [comment]
You can already do that by placing a `.gdriveignore` file in the root of sync folder. Mentioned in readme [here](https://github.com/gdrive-org/gdrive#gdriveignore)

**Comment by nlistgarten** [comment]
@mbenlioglu Aaaaaaaaahhhhh I need to read the readme more carefully! Closing.
