### ISSUE TITLE
How to sync download files added in syncable drive dir to local path?

### ISSUE THREAD

**Issue by jyakaranda** [gdrive-org/gdrive#449]
I added 3 files to syncable drive directory via google drive, I've tried to sync those remote files with command "gdrive sync download fileId path"(fileId is the syncable drive directory's id), and I got output:
```
Starting sync...
Collecting file information...
Found 0 local files and 0 remote files
```
but I actually added 3 files in remote drive directory.
How can I sync download those new added files in syncable drive directory?

**Comment by mbenlioglu** [comment]
`sync` option of `gdrive` marks files with a special appProperty field while initializing the folder. So if you added something from outside that will miss this tag and will be ignored. In other words new files should be added with `gdrive sync upload` command to be seen. There isn't a workaround for this that I can think of at the moment.

**Comment by jyakaranda** [comment]
> `sync` option of `gdrive` marks files with a special appProperty field while initializing the folder. So if you added something from outside that will miss this tag and will be ignored. In other words new files should be added with `gdrive sync upload` command to be seen. There isn't a workaround for this that I can think of at the moment.

Understood, thank you very much!
