### ISSUE TITLE
Is there any logs?

### ISSUE THREAD

**Issue by luisduenas** [gdrive-org/gdrive#452]
Hi, i'm using gdrive in a cronjob that runs in the middle of the night, for some reason it stopped to work and im wondering if there's any gdrive logs where i can take a look at, i think the problem is the space available in the drive account but i just wanted to know if there is any log already or if i have to make one on the script side.

Thanks

**Comment by mbenlioglu** [comment]
Hi Luis,
gdrive outputs errors to stdout, so you can keep the outputs by editing your cronjob something like this

    0 3 * * * /path/to/gdrive params > /var/log/gdrive.log 2>&1

**Comment by luisduenas** [comment]
that should work, thank you

**Comment by luisduenas** [comment]
Just for future references, i just apply the changes and worked as expected.
