### ISSUE TITLE
How to Create folder and insert file in

### ISSUE THREAD

**Issue by loctong** [gdrive-org/gdrive#454]

**Comment by mbenlioglu** [comment]
Can you explain the issue you're facing?

**Comment by loctong** [comment]
I mean how to create new folder and insert files or folders in it same time, sr for my English

**Comment by mbenlioglu** [comment]
You can upload a local folder (and all its contents recursively) directly into drive using this command

     $ gdrive upload -r /path/to/folder/

This will create the folder first then upload whatever it has inside to drive. You can find the reference from readme [here](https://github.com/gdrive-org/gdrive#upload-file-or-directory)

**Comment by loctong** [comment]
thanks for your reply.
