### ISSUE TITLE
Could I allow spacific directory for gdrive access???

### ISSUE THREAD

**Issue by thearabbit** [gdrive-org/gdrive#457]
In my drive directory structure:
```
/private_a
/private_b
/mygdrive
```
I wold like to allow `Gdrive` to access only `mygdrive` directory.
Please help me

**Comment by mbenlioglu** [comment]
Unfortunately, that can't be done. Google provides oauth token for the entire drive and not for some selected containers or files. What you can do is to share "mygdrive" to some other account and give gdrive access to that account. This way private_* folders won't be accessed.

If what you want is for gdrive to have its own space, where neither any other app (including web gui I believe) can access to it nor gdrive can access to any other files. That can be added as a feature, in future.

**Comment by thearabbit** [comment]
Very thanks for your reply.
👍
