### ISSUE TITLE
Compile issue

### ISSUE THREAD

**Issue by Loart** [gdrive-org/gdrive#459]
Having issues compiling. I've followed steps from [This tutorial](https://github.com/tripLr/gdrive/blob/master/TUTORIAL-INSTALL-Windows#L85l) and #426. When I run the compiled exe it just runs a cmd prompt and then closes instantly and no commands work.

**Comment by mbenlioglu** [comment]
This sounds like you tried to use it by double-clicking the exe file. You should open a cmd then navigate to where gdrive.exe is then run commands from cmd there

**Comment by mbenlioglu** [comment]
Closed due to inactivity
