### ISSUE TITLE
Delete more than one file

### ISSUE THREAD

**Issue by fabianskibr** [gdrive-org/gdrive#463]
In my backup folder on google drive there are 5 files with the same name and I want to delete all of them.

I currently use this in a schipt shell to erase my old backup files.

`gdrive list -q "'FOLDERID' in parents" | grep MYFILE | awk '{ print $1}'`

When using this command to list the files the result generated is this

```
FILEID-1
FILEID-2
FILEID-3
FILEID-4
FILEID-5
```

To delete the file I simply used the gdrive delete FILEID command but this worked only when there was only one file, now that there are several results it does not delete the files:

`No valid arguments given, use 'gdrive help' to see available commands`

Is there any way to delete all?

**Comment by mbenlioglu** [comment]
Here's what I tried:
```
My Drive:
|--- tests
      |--- folder
            |--- file.txt
            |--- file.txt
            |--- file.txt
```

Script:
```bash
user@Comp:~$ gdrive list -q "'1VO-iDPmf1iwj29hCoZK48sHR0RGyulll' in parents"
Id                                  Name       Type   Size     Created
18zeSgvFrITHp33ui6p9yGe4ul6ViWkvZ   file.txt   bin    16.0 B   2019-06-05 01:54:31
1AlkD6ZN8C2DSkNPzDjfCWOyYYASg98Ue   file.txt   bin    16.0 B   2019-06-05 01:54:39
1_mNRjTwTP86FPbbTDQQrcuSDwyWXXTpX   file.txt   bin    16.0 B   2019-06-05 01:54:19
user@Comp:~$ gdrive list -q "'1VO-iDPmf1iwj29hCoZK48sHR0RGyulll' in parents" | grep file.txt | awk '{ print $1}' | xargs -L1 gdrive delete
Deleted 'file.txt'
Deleted 'file.txt'
Deleted 'file.txt'
user@Comp:~$ gdrive list -q "'1VO-iDPmf1iwj29hCoZK48sHR0RGyulll' in parents"
Id   Name   Type   Size   Created
```
 It worked normally as I'd expect.

**Comment by fabianskibr** [comment]
Thanks!!!
