### ISSUE TITLE
How download to custom directory

### ISSUE THREAD

**Issue by goodandrewsoft** [gdrive-org/gdrive#469]
For example
how download to `f:\download` ?

`gdrive.exe download 0B3X9GlR6EmbnZ1NGS25FdEVlWEk -O f:\download` or how ?

And, how save with another filename?

**Comment by mbenlioglu** [comment]
You can specify download path like this:

```console
$ gdrive.exe download --path "c:\path\to\download\directory" <FILE ID> 
```
Or you can redirect from stdout and can save with another name
```console
$ gdrive.exe download <FILE_ID> --stdout > "C:\Path\to\Directory\Filename"
```
