### ISSUE TITLE
Remove Old Backups In GDrive

### ISSUE THREAD

**Issue by BeanHubbleday** [gdrive-org/gdrive#473]
Hi All,

Had a look through various older posts but to no avail.

I have a crontab script that copies all of my important folders to another folder, on the server _/backups_/.

I then use another crontab file, later on in the day, that copies all the contents of _/backups/_ to my folder, in GDrive called _BACKUPS_.

I want to keep each backup folder for 5 days and then delete them, can anybody recommend a way to delete all folders inside of a folder but not the parent folder itself?

Thanks for your help!

**Comment by mbenlioglu** [comment]
You can try something like 
```console
~$ gdrive list -q "('FOLDER_ID' in parents) and modifiedTime < '$(date -d 5days-ago -Iseconds)'" --no-header --max 0 | cut -d" " -f1 - | xargs -n1 gdrive delete -r
```
