### ISSUE TITLE
Download links for Linux are broken

### ISSUE THREAD

**Issue by devova** [gdrive-org/gdrive#479]
I can't download neither x64 or x86 executable. But I was able to do that month ago.

**Comment by nyuszika7h** [comment]
Can confirm, x64 is 404, and x86 says "Sorry, this file is infected with a virus."

**Comment by bmestanov** [comment]
Receiving 404 for x64 as well

**Comment by bszazulla** [comment]
404 here too.

Does anyone have another link with x64 already downloaded?

**Comment by PaschalisSk** [comment]
The old one compiled with the previous go version can be found [here](https://docs.google.com/uc?id=0B3X9GlR6EmbnQ0FtZmJJUXEyRTA&export=download).
The link was found in [this commit log](https://github.com/gdrive-org/gdrive/commit/29ca5a922a95b9ca1f09e1ad51bc853a50d6b888).

**Comment by mbenlioglu** [comment]
Apparently drive doesn't like the compiled binaries (but was fine with the previous versions) so I moved compiled binaries to github releases. And updated links in Readme too.

**Comment by devova** [comment]
Thank you very much.
