### ISSUE TITLE
gdrive has not been verified by Google

### ISSUE THREAD

**Issue by ferreirafm** [gdrive-org/gdrive#507]
Hi folks, 
I have tried to change the gdrive to another google account and got following message:
"This app has not been verified yet by Google in order to use Google Sign In."
Is it temporary? It there any overcome to that?

**Comment by panoslouk** [comment]
Same issue here

**Comment by aisingio** [comment]
build your own application with your own client_id and client_secret,see [https://github.com/gdrive-org/gdrive/issues/392](url)
click advance and allow your application to access your drive data when auth your application in your browser

**Comment by ferreirafm** [comment]
The problem has been solved following the:   
TUTORIAL: How to get rid of 403 Errors [#426](https://github.com/gdrive-org/gdrive/issues/426)
