### ISSUE TITLE
Could use file/directory name instead of ID to upload, remove ....?

### ISSUE THREAD

**Issue by thearabbit** [gdrive-org/gdrive#522]
For example in My Drive (Google Drive)
```
/backup-data
   2019-12-01.zip
   2019-12-02.zip
   myFile.zip
```
I would like to delete directory name `/backup-data` or by file name `/backup-data/myFile.zip`
Please help me

**Comment by cfrantzol** [comment]
Yeah this would be very very useful because it is not possible to delete anything by OS name you need to use the Google file identifier. I too had no chance solving this issue, hope someone will help here.

**Comment by thearabbit** [comment]
thanks for your reply.
the other hand, I could remove all file with modify date query  in spacifec directory ID???

**Comment by mdobydullah** [comment]
As far as I know, there is no way to use the file/folder name instead of ID in GDrive.

I've tested [odeke-em/drive](https://github.com/odeke-em/drive). Using this one, you're able to use name.

Thanks.

**Comment by thearabbit** [comment]
thanks again @mdobydullah
