### ISSUE TITLE
This app has not been verified yet by Google in order to use Google Sign In.

### ISSUE THREAD

**Issue by quantrpeter** [gdrive-org/gdrive#535]
hi, i met this issue:

This app has not been verified yet by Google in order to use Google Sign In.

![image](https://user-images.githubusercontent.com/50471577/76700050-5276fa00-66ee-11ea-82ef-543ca04d25e2.png)

**Comment by thg303** [comment]
same issue here. any work-around?

**Comment by quantrpeter** [comment]
yes, it work. Super thanks
