### ISSUE TITLE
Windows Installation Problems

### ISSUE THREAD

**Issue by nykekana** [gdrive-org/gdrive#551]
Hello, 

I downloaded the gdrive-windows-x64.exe file, but I when I run gdrive about, I am met with the error below:

![image](https://user-images.githubusercontent.com/45674574/81320052-920ef200-905e-11ea-90c6-c7718e64bb6e.png)

Did I miss a step? How can I resolve this.

Thanks in advance!

**Comment by Nailz1911** [comment]
`gdrive-windows-x64.exe about`

**Comment by nykekana** [comment]
Glorious! It worked! Thank you so much @Nailz1911!

A quick note for people who encounter a similar problem in the future: make sure you are in the directory where you are storing gdrive-windows-x64.exe.
